p2 = imread('img1.png');
p2= double (p2);
Bit_scling= bitget (p2,1);
subplot(3,3,1); imshow(Bit_scling); title('Plane 1');
Bit_scling= bitget (p2,2);
subplot(3,3,2); imshow(Bit_scling); title('Plane 2'); 
Bit_scling= bitget (p2,3);
subplot(3,3,3); imshow(Bit_scling); title('Plane 3'); 
Bit_scling= bitget (p2,4);
subplot(3,3,4); imshow(Bit_scling); title('Plane 4');
Bit_scling= bitget (p2,5);
subplot(3,3,5); imshow(Bit_scling); title('Plane 5'); 
Bit_scling= bitget (p2,6);
subplot(3,3,6); imshow(Bit_scling); title('Plane 6');
Bit_scling= bitget (p2,7);
subplot(3,3,7); imshow(Bit_scling); title('Plane 7');
Bit_scling= bitget (p2,8);
subplot(3,3,8); imshow(Bit_scling); title('Plane 8');
Bit_scling= bitget (p2,9);
subplot(3,3,9); imshow(Bit_scling); title('Plane 9');